name: kong_comic
description: "A comic app."
publish_to: 'none'

version: 1.3.1+162

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: 3.44.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: any
  intl: any
  sqlite3: ^3.5.1
  flutter_qjs:
    path: packages/flutter_qjs
  crypto: ^3.0.6
  dio: ^5.9.2
  html: ^0.15.6
  pointycastle: ^4.0.0
  url_launcher: ^6.3.2
  path: ^1.9.0
  photo_view:
    path: packages/photo_view
  mime: ^2.0.0
  share_plus: ^12.0.1
  package_info_plus: ^9.0.1
  scrollable_positioned_list:
    path: packages/flutter.widgets/packages/scrollable_positioned_list
  flutter_reorderable_grid_view: ^5.4.0
  uuid: ^4.5.1
  app_links: ^7.0.0
  sliver_tools: ^0.2.12
  flutter_file_dialog: ^3.0.3
  zip_flutter: ^0.0.13
  archive: ^4.0.7
  lodepng_flutter:
    path: packages/lodepng_flutter
  webdav_client:
    path: packages/webdav_client
  local_auth: ^3.0.1
  local_auth_android: ^2.0.9
  local_auth_darwin: ^2.0.3
  wakelock_plus: ^1.2.14
  flutter_saf:
    path: packages/flutter_saf
  dynamic_color: ^1.8.1
  syntax_highlight: ^0.5.0
  flutter_7zip:
    path: packages/flutter_7zip
  flex_seed_scheme: ^4.0.1
  flutter_localizations:
    sdk: flutter
  yaml: ^3.1.3
  cached_network_image: ^3.4.0
  file_selector: ^1.1.0
  hugeicons: ^1.0.0
  battery_plus: ^7.0.0
  flutter_memory_info: ^0.0.3
  desktop_webview_window:
    path: packages/flutter_desktop_webview/packages/desktop_webview_window
  shimmer_animation: ^2.2.2
  flutter_inappwebview: ^6.1.5
  window_manager: ^0.5.1
  display_mode: ^0.0.2
  enough_convert: ^1.6.0
  flutter_staggered_grid_view: ^0.7.0
  workmanager: ^0.10.7
  flutter_local_notifications: ^22.3.0
  sentry_flutter: ^8.14.2
  flutter_markdown_plus: ^1.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_to_debian: 
    path: packages/flutter_to_debian

flutter:
  uses-material-design: true
  assets:
    - assets/translation.json
    - assets/init.js
    - assets/app_icon.png
    - assets/tags.json
    - assets/tags_tw.json
    - assets/opencc.txt
# fonts:
